kind: pipeline
name: default

steps:
- name: test
  image: supla/supla-cloud
  commands:
#  - mkdir .npm && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y --no-install-recommends nodejs && npm install -g npm@5 && apt-get autoremove
#  - cd src/Frontend && npm prune && npm install && npm run build && cd ../..
  - cp app/config/parameters.yml.drone app/config/parameters.yml
  - wget https://raw.githubusercontent.com/composer/getcomposer.org/e3e43bde99447de1c13da5d1027545be81736b27/web/installer -O - -q | php -- --quiet --1
  - php composer.phar install
#  - php composer.phar run-script lint
  - ./vendor/bin/phpunit -c app --stop-on-error --stop-on-failure

services:
- name: database
  image: mysql:5.7.20
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: supla_test
    MYSQL_USER: drone
    MYSQL_PASSWORD: ~
